name: balamh.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0a08'
    - '#b4d2f4'
    - '#728299'
    - '#3d3c3a'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
