name: balamh.com
favicon: null
layout_spectrum: 0.51784
typography_spectrum: 0.49277
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0a08'
    - '#b4d2f4'
    - '#728299'
    - '#3d3c3a'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
