name: null
favicon: null
layout_spectrum: 0.6763782140333205
typography_spectrum: 0.20097780670039356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3684652929659933
  lightness: 0.9382604754064232
  saturation: 0.8829409175086766
  rhythmicContrast: 0.2597230887040496
purpose: []
